---
- name: Instalar MySQL
  hosts: Master
  vars: 
    mysql_root_password: Montechelo2022*
  become: yes
  tasks:
      - name: Instalar wget
        yum: name=wget state=installed

      - name: Instalar Python
        yum: name=MySQL-python state=installed

      - name: Instalar llaves
        get_url: url=https://repo.mysql.com/RPM-GPG-KEY-mysql dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql

      - name: Descargar libreria MySQL
        get_url: 
          url: https://repo.mysql.com/mysql80-community-release-el7-6.noarch.rpm 
          dest: /usr/mysql/mysql80-community-release-el7-6.noarch.rpm

      - name: Instalar el rpm
        yum: 
          name: /usr/mysql/mysql80-community-release-el7-6.noarch.rpm 
          state: present

      - name: Instalar MySQL
        yum: name=mysql-server state=installed

      - name: Inicar proceso MySQL
        service: name=mysqld state=started

      - name: Crear baseDatos
        mysql_db: name=project state=present login_user=root login_password={{ mysql_root_password }}

      - name: reiniciar mysql
        service: name=mysqld state=restarted

